[build]
builder = "DOCKERFILE"
dockerfilePath = "src/money-manager-web/Dockerfile"
watchPatterns = ["src/money-manager-web/**"]

[build.args]
NEXT_PUBLIC_API_URL = "${{API_URL}}"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
