[build]
builder = "DOCKERFILE"
dockerfilePath = "src/MoneyManager.Frontend/Dockerfile"
watchPatterns = ["src/MoneyManager.Frontend/**"]

[build.args]
NEXT_PUBLIC_API_URL = "${{API_URL}}"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
